

services:
  db:
    image: postgres:16
    container_name: anunciosloc-db
    env_file: .env                # lê variáveis do .env na raiz (ou ./postgres/.env)
    ports:
      - "5433:5432"               # expõe ao host para conectar do Codespace / host
    volumes:
      - ./postgres/db_data:/var/lib/postgresql/data   # bind mount (dados visíveis no projeto)
      - ./postgres/init:/docker-entrypoint-initdb.d:ro
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER}"]
      interval: 5s
      timeout: 5s
      retries: 5

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: anunciosloc-backend
    env_file: backend/.env
    depends_on:
      db:
        condition: service_healthy
    environment:
      DATABASE_URL: postgres://${POSTGRES_USER}:${POSTGRES_PASSWORD}@db:5432/${POSTGRES_DB}
    ports:
      - "3000:3000"
    volumes:
      - ./backend:/usr/src/app
    command: npm run dev   # ou "npm start" em produção

volumes:
  pgdata:

